name: tabletop
# version: 0.1.0
author: Michael Borden
maintainer: michael@quiet.space
copyright: Michael Borden 2018
license: BSD3

github: taksuyu/tabletop

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  # - -Wmissing-import-lists

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

default-extensions:
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NamedFieldPuns
  - OverloadedStrings
  - TupleSections
  - TypeApplications

dependencies:
  - base
  - aeson
  - async
  - backhand
  - bytestring
  - game-of-ur
  - http-types
  - katip
  - mtl
  - random
  - stm
  - stm-containers
  - text
  - transformers
  - transformers-base
  - unagi-chan
  - unliftio
  - uuid
  - vector
  - wai
  - wai-websockets
  - warp
  - websockets

library:
  source-dirs: src

executables:
  tabletop:
    main: Main.hs
    dependencies: tabletop
    ghc-options: *exe-ghc-options

# FIXME: I want there to be tests; I just don't know what I would end up
# testing.
#
# tests:
#   spec:
#     main: Spec.hs
#     source-dirs: test
#     dependencies:
#       - tabletop
#       - hspec
#       - hspec-wai
#       - hspec-wai-json
#     ghc-options: *exe-ghc-options
