name: tabletop
# version: 0.1.0
author: Michael Borden
maintainer: michael@quiet.space
copyright: Michael Borden 2018
license: BSD3

github: taksuyu/tabletop

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  # - -Wmissing-import-lists

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

default-extensions:
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NamedFieldPuns
  - OverloadedStrings
  # - PartialTypeSignatures
  - TupleSections
  - TypeApplications

dependencies:
  - base
  - aeson
  - async
  - backhand
  - bytestring
  - config-ini
  - containers
  - game-of-ur
  - generic-lens
  - http-types
  - katip
  # - microlens
  - microlens-platform
  - mtl
  - random
  - stm
  - stm-containers
  - text
  - transformers
  - transformers-base
  - unagi-chan
  - unliftio
  - uuid
  - vector
  - wai
  - wai-websockets
  - warp
  - websockets

library:
  source-dirs: src

executables:
  tabletop:
    main: Main.hs
    dependencies: tabletop
    ghc-options: *exe-ghc-options

tests:
  tabletop-test:
    main: Test.hs
    source-dirs: test
    dependencies:
      - tabletop
      - hedgehog
      - unique
    ghc-options: *exe-ghc-options
    default-extensions:
      - TemplateHaskell
