resolver: lts-12.6

packages:
  - .

extra-deps:
  - katip-0.6.0.0
  - serversession-backend-redis-1.0.3
  - unagi-chan-0.4.0.0

  - git: https://github.com/quietspace/backhand.git
    commit: 0bb62222e60fc114ff679158fb56c955c6521a33
    subdirs:
      - backhand
  - git: https://github.com/taksuyu/game-of-ur.git
    commit: 21e49688b0cfd60cc732aa3849546b6a3a3543fa
