version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build
    steps:
      - run:
          name: System Information
          command: locale
          command: stack --version

      # TODO: We can cache git objects in the future.
      - checkout

      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - stack-v2-ghc-8.4.3-{{ .Branch }}-{{ checksum "stack.yaml" }}
            - stack-v2-ghc-8.4.3-{{ .Blanch }}-
            - stack-v2-ghc-8.4.3-
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
          command: stack build --test --dependencies-only
      - save-cache:
          name: Cache Dependencies
          key: stack-v2-ghc-8.4.3-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work

      - run:
          name: Build/Test tabletop
          command: stack build --test --pedantic
