version: 2
jobs:
  build:
    docker:
      - image: ubuntu:17.10
    steps:
      - run: apt update && apt install -y wget
      - run: wget -qO- https://get.haskellstack.org/ | sh
      - run: stack --version
        # TODO: We can cache git objects in the future.
      - checkout
      - restore_cache:
          keys:
            - stack-v1-{{ .Branch }}-{{ .Revision }}
            - stack-v1-{{ .Branch }}
            - stack-v1

      - run: stack build --fast --pedantic --haddock
      - save_cache:
          key: stack-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/.stack"
